sudo: true
language: python

before_install:
- sudo apt-get update -qq
- sudo apt-get -y install squashfs-tools uuid

install:
  - pip install ansible
  - pip install docker-py
services:
  - docker
script:
- ./run_squashible.sh
