---
language: python
python: "2.7"
sudo: required
dist: trusty

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq squashfs-tools uuid python-apt python-pycurl

install:
 - pip install ansible
 - pip install docker-py

script:
 - ./run_squashible.sh
