---

- name: Initial setup and bootstrap
  hosts: builder
  tasks:
    - include: utils/requirements-check.yml
    - include: utils/pre-bootstrap.yml
    - include: utils/build_chroot_docker.yml

- name: Create minimal live image
  hosts: chroot
  roles:
    - minimal
