---

  - name: Upgrade and install minimum package set
    shell: "{{item}}"
    with_items:
      - yum clean all
      - yum -y upgrade
      - yum -y install {{ minimal_packages['RedHat'] | join (" ") }}

  - name: Set multi-user target as the default systemd target
    file: src=/lib/systemd/system/multi-user.target dest={{item}}
      state=link force=yes
    with_items:
      - /lib/systemd/system/default.target
      - /etc/systemd/system/default.target
