---

  - name: Install ctorrent x64 binary for Dracut torrent support
    copy:
      src: ctorrent
      dest: /usr/bin/ctorrent
      mode: 0755

  - name: Add dracut config to enable livenet module
    copy:
      src: dracut-config
      dest: /etc/dracut.conf.d/dracut.conf
      owner: root
      group: root
      mode: 0644

  - name: Add dracut live filesystem boot patch
    copy:
      src: 0001-Testing-live-fileystem-boot.patch
      dest: /tmp/0001-Testing-live-fileystem-boot.patch

  - name: Apply dracut live filesystem boot patch
    command: patch -p0 /usr/lib/dracut/modules.d/90dmsquash-live/dmsquash-live-root.sh /tmp/0001-Testing-live-fileystem-boot.patch

  - name: Remove live filesystem boot patch
    file:
      path: /tmp/0001-Testing-live-fileystem-boot.patch
      state: absent

  - name: Add dracut torrent retrieval patch
    copy:
      src: 0002-Testing-torrent-retrieval.patch
      dest: /tmp/0002-Testing-torrent-retrieval.patch

  - name: Apply dracut torrent retrieval patch
    command: patch -p0 /usr/lib/dracut/modules.d/45url-lib/url-lib.sh /tmp/0002-Testing-torrent-retrieval.patch

  - name: Remove torrent retrieval patch
    file:
      path: /tmp/0002-Testing-torrent-retrieval.patch
      state: absent

  - name: Clean up state files
    file:
      dest: "/etc/firstboot.d/state"
      state: "{{ item }}"
    with_items:
      - absent
      - directory

  - name: Remove xapi files
    file:
      dest: "/var/lib/xcp"
      state: "{{ item }}"
    with_items:
      - absent
      - directory

  - name: Remove xapi files
    file:
      dest: "/etc/firstboot.d/data/management.conf"
      state: "absent"

  - name: Disable firstboot
    service: name=firstboot enabled=no

  - name: Apply xenserver overlay
    copy: src=overlay/ dest=/
