---

  - name: Import OS specific variables
    include_vars: "{{ ansible_distribution }}_{{ ansible_architecture }}.yml"

  - include: debian.yml
    when: ansible_distribution == 'Debian'

  - include: redhat.yml
    when: ansible_os_family == "RedHat"

  - include: opensuse.yml
    when: ansible_os_family == "Suse"

  - include: ubuntu.yml
    when: ansible_distribution == "Ubuntu"

  - name: Checkout Openstack Nova
    git: 
      repo: https://github.com/openstack/nova.git
      dest: /opt/nova
      version: master
      depth: 1

  - name: Install pip
    easy_install: 
      name: pip
      state: latest

  - name: Install modules
    pip:
      name: virtualenv

  - name: Create directories
    file:
      path: /opt/openstack/nova/{{ openstack_nova_branch }}
      state: directory

  - name: Link to nova-master directory
    file:
      src: /opt/openstack/nova/{{ openstack_nova_branch }}
      dest: /opt/openstack/nova/current
      state: link

  - name: Install build_nova_venv.sh
    template:
      src: build_nova_venv.sh.j2
      dest: /opt/openstack/nova

  - name: Run build_nova_venv.sh
    command: ./build_nova_venv.sh
    args:
      chdir: /opt/openstack/nova

  - name: Add openstack-nova-compute service
    copy:
      src: openstack-nova-compute.service
      dest: /usr/lib/systemd/system/openstack-nova-compute.service
      owner: root
      group: root
      mode: 0644

  - name: Enable systemd services
    file: 
      src: "{{ item.path }}"
      dest: "{{ item.dest }}"
      state: link
    with_items:
      - { path: '/usr/lib/systemd/system/openstack-nova-compute.service', dest: '/etc/systemd/system/multi-user.target.wants/openstack-nova-compute.service' }

  - name: Cleanup
    file:
      path: /opt/nova
      state: absent
