---

  - name: Set nova_venv__packages
    set_fact:
      nova_venv_packages: "{{ nova_venv_packages | join (' ') }}"

  - name: Install nova_venv_packages
    shell: "{{ ansible_pkg_mgr }} -y install {{ nova_venv_packages }}"

  - name: Add openstack-nova-compute service
    copy:
      src: openstack-nova-compute.service
      dest: /usr/lib/systemd/system/openstack-nova-compute.service
      owner: root
      group: root
      mode: 0644

  - name: Enable systemd services
    file:
      src: "{{ item.path }}"
      dest: "{{ item.dest }}"
      state: link
    with_items:
      - { path: '/usr/lib/systemd/system/openstack-nova-compute.service', dest: '/etc/systemd/system/multi-user.target.wants/openstack-nova-compute.service' }
