---
kvm_packages:
   - bridge-utils
   - dosfstools
   - dosfstools-dbg
   - genisoimage
   - kpartx
   - libvirt-bin
   - multipath-tools
   - nfs-common
   - open-iscsi
   - python-libguestfs
   - python-libvirt
   - qemu
   - qemu-utils
   - sysfsutils
   - vlan
   - multipath-tools
