---
kvm_packages:
  - bridge-utils
  - genisoimage
  - kpartx
  - libvirt-bin
  - open-iscsi
  - python-libguestfs
  - python-libvirt
  - qemu
  - qemu-utils
  - sysfsutils
  - vlan
  - nfs-common
  - dosfstools
  - dosfstools-dbg
  - multipath-tools
  - qemu-system
  - qemu-system-arm
  - qemu-system-mips
  - qemu-system-ppc
  - qemu-system-sparc
  - qemu-system-x86
  - qemu-system-misc
  - qemu-block-extra
  - qemu-utils
  - qemu-user
