---

  - name: Mount proc inside the chroot
    mount: >
        name=/proc
        fstype=proc
        src=none
        state=present

  - name: Set /etc/resolv.conf
    lineinfile: >
        dest=/etc/resolv.conf
        line="{{item}}"
        create=yes
    with_items:
      - 'nameserver 8.8.8.8'
      - 'nameserver 8.8.4.4'

  - name: Ensure /sys/fs/selinux mount path exists
    file: >
        path=/sys/fs/selinux
        state=directory
    when: selinux_enabled

  - name: Mount selinuxfs in chroot
    local_action: >
        mount
        name={{hostvars['localhost']['livepath']}}/sys/fs/selinux
        src=selinuxfs
        fstype=selinuxfs
        state=present
    when: selinux_enabled

  - include: debian/main.yml
    when: ansible_os_family == 'Debian'

  - include: redhat/main.yml
    when: ansible_os_family == "RedHat"
