---

  - name: Disable daemon startup with policy-rc.d file
    copy: src=debian/usr-sbin-policy-rc.d dest=/usr/sbin/policy-rc.d
      owner=root group=root mode=0755

#  - name: Set repo name to universe to pull in some live-boot packages
#    apt_repository: repo='deb http://mirror.rackspace.com/ubuntu {{ ansible_distribution_release }} main universe' state=present

  - name: Add ppa for dracut to fix some conflicts https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1109029 
    apt_repository: repo='deb http://ppa.launchpad.net/morty/dracut-release/ubuntu {{ ansible_distribution_release }} main' state=present

  - name: Set minimal_packages
    set_fact:
      minimal_packages: "{{ minimal_packages | join (' ') }}"

  - name: Install minimum packages
    shell: "{{ ansible_pkg_mgr }} --force-yes -qq install {{ minimal_packages }}"

  - name: Add support for DNS resolution in initramfs
    lineinfile: >
      dest=/etc/live/boot.conf
      line="LIVE_DNS=true"
      create=yes
      state=present

  - name: Remove hostname file, let live-config take care of it
    file: path=/etc/hostname state=absent

  - name: Install the kernel and regenerate initramfs
    apt: pkg=linux-generic state=latest

  - name: Don't let live-config disable ssh password authentication
    lineinfile: dest=/lib/live/config/1160-openssh-server
        regexp="PasswordAuthentication"
        state=absent

  - name: Add live user (for testing)
    user: name=live shell=/bin/bash groups=sudo append=yes
      password="$6$uf0amHdCN0H8PwWk$zKoAF4khAjunE/pnq0Q4iMU69t7gj2mvaKku3YE5k3/bVl.H9DcwOnlqBY23yTTcidp2CjknV38rgSro62vpC/"

  - name: Deny live user from ssh, only allow via console
    lineinfile: dest=/etc/ssh/sshd_config line="DenyUsers live"

  - name: Add dracut config to enable livenet module
    copy: src=ubuntu/dracut-config dest=/etc/dracut.conf
      owner=root group=root mode=0644

  - name: Copy test livenet patches for bugzilla #1280103
    copy:
      src: ubuntu/dracut/livenet-generator.sh
      dest: /usr/lib/dracut/modules.d/90livenet/livenet-generator.sh
      mode: 0755
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "15.10"

  - name: Copy test livenet patches for bugzilla #1280103
    copy:
      src: ubuntu/dracut/module-setup.sh
      dest: /usr/lib/dracut/modules.d/90livenet/module-setup.sh
      mode: 0755
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == "15.10"
